# Generated by Django 5.0.6 on 2024-07-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('certificate_number', models.CharField(max_length=255, unique=True)),
                ('policy_number', models.CharField(max_length=255, unique=True)),
                ('insured', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('insurance_type', models.CharField(max_length=255)),
                ('premium', models.DecimalField(decimal_places=0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payement_method', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=255)),
                ('insured', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=150)),
                ('prime', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(default='Assuré', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=150)),
                ('agency', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=50)),
                ('responsible', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('insured', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('amount_th', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrimeAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField()),
                ('date_fin', models.DateField()),
                ('prime', models.DecimalField(decimal_places=0, max_digits=10)),
                ('responsible', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=255)),
                ('payement_method', models.CharField(max_length=50)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amana.disbursement')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amana.disbursement')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amana.disbursement')),
            ],
        ),
        migrations.CreateModel(
            name='SexUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amana.sex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmallCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amana.disbursement')),
            ],
        ),
    ]
